on: pull_request

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_KEY }}

jobs:
  run-test:
    name: Runs tests
    runs-on: windows-latest
    steps: 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3.7.0
        - uses: actions/checkout@v2
        - name: Install Dependencies
          run: npm install
        - name: Check Build
          run: npm run build
        - name: Test Mock API
          run: npm run test-mock
        - name: Test Components and Functions
          run: npm run test
        - name: Check linting
          run: npm run lint
        
          
    
